#! /bin/bash
#export MATLAB_2015b_PATH="~/local_MATLAB/v90" # Deactivated 13 August 2019


common_code_path="/mnt/clustertmp/common/rja20_dev/"
export MATLAB_EXEC_PATH="${common_code_path}/matlab_execs_for_SAMBA/"

export BIGGUS_DISKUS=/mnt/munin2/Badea/Lab/mouse
export WORKSTATION_DATA=/mnt/munin2/Badea/Lab/
export MATLAB_2015b_PATH="${common_code_path}/MATLAB2015b_runtime/v90"
#export MATLAB_JAVA=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre
export MATLAB_JAVA=/mnt/clustertmp/common/rja20_dev/jres
# Control which version of perl we're using
perlbrew switch perl-5.16.3

# For email support, need to add
export NOTIFICATION_EMAIL=${USER}@duke.edu
