#!/bin/bash
# Custom SAMBA startup with frozen pipeline code including pipeline_utilities(:D ) shush now
if [[ -d $SAMBA_PATH ]];then
    SPath=${SAMBA_PATH};
else
    SPath="${HOME}/SAMBA";
fi
echo "frozen dance at ${SPath}";
## For BIAC:
PU_path="${SPath}/../pipeline_utilities";
if [[ ! -d "${PU_path}" ]];then
    PU_path="${HOME}/pipeline_utilities";
fi
export RADISH_PERL_LIB=${PU_path};

#export RADISH_PERL_LIB="${HOME}/SAMBA/local/lib/perl5:${RADISH_PERL_LIB}";

local_perl="${SPath}/local/lib/perl5";
if [[ -d "${local_perl}" ]];then
    export RADISH_PERL_LIB="${local_perl}:${RADISH_PERL_LIB}";
fi

echo "adjust lib path from $RADISH_PERL_LIB";
declare -x RADISH_PERL_LIB=$(echo $RADISH_PERL_LIB|sed -E "s:${WORKSTATION_HOME}/+shared/+pipeline_utilities:${SPath}/.pipeline_utilities:g");
echo "to $RADISH_PERL_LIB";
echo ${SPath}/vbm_pipeline_start.pl $@
#sleep 2
echo " "
echo " "
sge_test=$(which qsub | grep sge | wc -l);
#if [[ ! 1 ]];then # For testing
if [[ $sge_test == 1 ]]; then
    sb_dir=${HOME}/SAMBA_sbatch;
    if [[ ! -d ${sb_dir} ]];then
	mkdir -m 775 ${sb_dir};
    fi
    
    date_tag=$(date --rfc-3339=seconds | tr ' ' '_' | tr ':' '.' | tr -d '-');
    name="SAMBA_pipeline_${date_tag}";
    sbatch_file="${HOME}/SAMBA_sbatch/${name}.bash";
    source_sbatch="${SPath}/SAMBA_SGE_job.bash";
    cp ${source_sbatch} ${sbatch_file};
    echo "#\$ -N ${name}" >> ${sbatch_file};
    echo "#\$ -o ${HOME}/testes_are_ballses";
    echo "${SPath}/vbm_pipeline_start.pl $@" >> ${sbatch_file};
    cmd="qsub -terse  -b y -V ${sbatch_file}";
#cmd="qsub -terse  -N SAMBA_pipeline -M ${USER}@duke.edu -m ea -o ${HOME}/SAMBA_sbatch/slurm-"'$JOB_ID'".out -e ${HOME}/SAMBA_sbatch/slurm-"'$JOB_ID'".out -b y -V ${SPath}/vbm_pipeline_start.pl $@";

echo $cmd;

echo " ";
echo " ";

   job_id=$($cmd | tail -1);
#qsub  ${SPath}/vbm_pipeline_start.pl $@;
   echo "JOB ID = ${job_id}";
   echo "";
   echo "To stop this instance of SAMBA pipeline please use the following command:";
   echo "qdel ${job_id}";
   sleep 3;

   #sb_file="${HOME}/SAMBA_sbatch/slurm-$job_id.out"; # This the behavior that I really want, but currently not getting!
   sb_file="${HOME}/${name}.bash.o${job_id}";

   touch ${sb_file}; #Make sure it exists so we can immediately call the tail command without risk of erroring out.
   tail -f "${sb_file}";
else
    ${SPath}/vbm_pipeline_start.pl $@;
fi
